name: Greetings

on: [issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@1c4688942c71f71d4f5502a26ea67c331730fa4d # v3.1.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hey there! 👋 Thank you for reaching out."
        pr-message: "Hey there! 👋 Thank you for creating a pull request."
